#!/usr/bin/env python3
"""Build narrated presentation assets for the Your Organization portal demo.

Inputs:
- demo_artifacts/* portal screenshots
- demo_artifacts/guided-walkthrough-narration.mp3 generated by Hermes TTS

Outputs:
- demo_artifacts/your-organization-portal-guided-walkthrough.pptx
- demo_artifacts/your-organization-portal-guided-walkthrough.pdf (via LibreOffice when available)
- demo_artifacts/your-organization-portal-guided-walkthrough-narrated.mp4
- demo_artifacts/your-organization-portal-guided-walkthrough-captions.srt
- demo_artifacts/guided-walkthrough-assets-readme.md
"""

from __future__ import annotations

import json
import math
import shutil
import subprocess
import textwrap
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_AUTO_SIZE
from pptx.util import Inches, Pt

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "demo_artifacts"
AUDIO = ARTIFACTS / "guided-walkthrough-narration.mp3"
PPTX = ARTIFACTS / "your-organization-portal-guided-walkthrough.pptx"
PDF = ARTIFACTS / "your-organization-portal-guided-walkthrough.pdf"
VIDEO = ARTIFACTS / "your-organization-portal-guided-walkthrough-narrated.mp4"
SRT = ARTIFACTS / "your-organization-portal-guided-walkthrough-captions.srt"
README = ARTIFACTS / "guided-walkthrough-assets-readme.md"
FRAMES = ARTIFACTS / "guided_frames"

W, H = 1280, 720
NAVY = "#07111f"
INK = "#101828"
MUTED = "#667085"
PANEL = "#f8fafc"
RED = "#b42318"
CYAN = "#32d5ff"
GREEN = "#12b76a"
BORDER = "#263447"
WHITE = "#ffffff"


@dataclass(frozen=True)
class Segment:
    title: str
    subtitle: str
    screenshot: str
    narration: str
    bullets: tuple[str, ...]
    accent: str = CYAN


SEGMENTS = [
    Segment(
        "Your Organization RAIccoon Operations Portal",
        "AI-narrated executive walkthrough",
        "dashboard.png",
        "Welcome to the Your Organization internal command portal. This is the operator cockpit for turning cyber research, portal tasks, OpenCTI hygiene, client context, and finished reports into one governed workflow.",
        ("One operating layer for research, reporting, clients, and governance", "Built around real operator workflow, not generic ticketing", "Demo uses synthetic artifacts and safe presentation data"),
        RED,
    ),
    Segment(
        "Dashboard: command-center visibility",
        "Start with what needs attention now",
        "dashboard.png",
        "We start on the dashboard. The goal is fast situational awareness: what is open, what is blocked, what is ready for review, what has been published, and where the operator should focus next. Instead of hunting across folders and chat threads, the portal shows the current queue, delivery status, and operational risk in one place.",
        ("Open / blocked / in-review work surfaced immediately", "Current priority queue replaces folder and chat archaeology", "Delivery status and operational risk in one view"),
    ),
    Segment(
        "Task board: governed work lifecycle",
        "Every work item has state, owner, client context, and history",
        "tasks.png",
        "Next is the task board. Work moves through a controlled lifecycle: todo, in progress, blocked, in review, accepted, and complete. Each item carries ownership, client context, due dates, quality signals, and history, so the team can see what needs action and why.",
        ("Todo → in progress → blocked/review → accepted/complete", "Ownership, due dates, comments, and QA signals travel with the task", "Operators can quickly identify stale, blocked, or review-ready work"),
    ),
    Segment(
        "Research intake: route work deliberately",
        "Threat intel, detections, hunting, IR triage, enrichment, malware analysis",
        "research.png",
        "The research intake screen is where new work enters the system. Threat intel, detection engineering, threat hunting, IOC enrichment, incident response triage, and malware analysis can all be routed from here. Malware sandboxing is deliberately gated: it only runs when the task is explicitly malware analysis and a sample has been provided.",
        ("Structured intake for the main cyber workflows", "Malware sandboxing is explicit and sample-gated", "Prompts and routing preserve analyst intent"),
        GREEN,
    ),
    Segment(
        "Documents: final-report source of truth",
        "Client-ready PDFs stay clean; drafts stay out of the delivery shelf",
        "documents.png",
        "The document library is the client-ready source of truth. Final PDFs are easy to find, while drafts, source bundles, and intermediate artifacts stay out of the finished report view. This keeps delivery clean and reduces confusion about what is safe to share.",
        ("Final PDFs only in the client-ready library", "Drafts, source bundles, and intermediates stay elsewhere", "Reduces ambiguity about what is safe to send"),
    ),
    Segment(
        "Clients: connect research to stakeholder value",
        "Reports, detections, recommendations, and engagement context in one place",
        "clients.png",
        "Client profiles connect the operational work to stakeholder value. They scope briefs, detections, recommendations, engagement context, and reporting priorities, so outputs are grounded in the client environment rather than generic research.",
        ("Client and engagement context travels with work", "Briefs and detections align to stakeholder needs", "Outputs become client-grounded, not generic"),
    ),
    Segment(
        "Operator assist: keep collaboration tied to the work",
        "Prompt capture, context summaries, and follow-up actions stay attached",
        "chat.png",
        "The chat and operator-assist surfaces make the workflow collaborative. The portal can help capture prompts, summarize task context, and keep follow-up actions tied to the work item instead of scattered across separate tools.",
        ("Collaborative context stays near the task", "Prompts and summaries become reusable workflow artifacts", "Follow-up actions are easier to recover and verify"),
        GREEN,
    ),
    Segment(
        "Security and governance by default",
        "Internal-only posture, MFA, admin controls, audit expectations, publication gates",
        "security.png",
        "Finally, security and governance are built into the workflow. MFA, admin controls, audit expectations, internal-only access, and explicit publication gates help make the portal useful without weakening operational discipline.",
        ("MFA and admin enforcement are part of the operator path", "Audit/export expectations support accountable operations", "Publication gates protect delivery quality"),
        RED,
    ),
    Segment(
        "The outcome: a repeatable cyber operating system",
        "Trackable intake, reviewable research, easy delivery, expandable automation",
        "dashboard.png",
        "The value is simple: Your Organization gets a repeatable operating system for cyber research and reporting. Intake becomes trackable, research becomes reviewable, final reports become easy to deliver, and the roadmap can keep expanding around automation, OpenCTI curation, detection engineering, and client-ready reporting.",
        ("Trackable intake", "Reviewable research", "Client-ready final reports", "Roadmap: automation, OpenCTI curation, detection engineering"),
        RED,
    ),
]


def run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=check)


def ffprobe_duration(path: Path) -> float:
    cp = run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "default=nw=1:nk=1", str(path)])
    return float(cp.stdout.strip())


def load_font(size: int, bold: bool = False):
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size=size)
    return ImageFont.load_default()


def wrap_text(draw: ImageDraw.ImageDraw, text: str, font, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current: list[str] = []
    for word in words:
        probe = " ".join(current + [word])
        if draw.textbbox((0, 0), probe, font=font)[2] <= width:
            current.append(word)
        else:
            if current:
                lines.append(" ".join(current))
            current = [word]
    if current:
        lines.append(" ".join(current))
    return lines


def draw_rounded_rectangle(draw: ImageDraw.ImageDraw, xy, radius: int, fill: str, outline: str | None = None, width: int = 1):
    draw.rounded_rectangle(xy, radius=radius, fill=fill, outline=outline, width=width)


def make_frame(segment: Segment, index: int, duration: float) -> Path:
    base = Image.new("RGB", (W, H), NAVY)
    draw = ImageDraw.Draw(base)
    # Background visual texture.
    draw.rectangle((0, 0, W, H), fill=NAVY)
    for i in range(0, W, 96):
        color = "#0b1d33" if i % 192 else "#10243c"
        draw.line((i, 0, i - 240, H), fill=color, width=2)
    draw.rectangle((0, 0, W, 80), fill="#0b1628")
    draw.rectangle((0, 675, W, H), fill="#08111f")
    draw.text((42, 24), "LOST BOYS CYBER", font=load_font(22, True), fill=WHITE)
    draw.text((1080, 27), f"{index:02d}/{len(SEGMENTS):02d}", font=load_font(20, True), fill=segment.accent)

    screenshot_path = ARTIFACTS / segment.screenshot
    screenshot = Image.open(screenshot_path).convert("RGB")
    # Place screenshot in a framed viewport.
    sx, sy, sw, sh = 52, 118, 748, 492
    screenshot.thumbnail((sw, sh), Image.Resampling.LANCZOS)
    shot_bg = Image.new("RGB", (sw, sh), "#0e1726")
    ox = (sw - screenshot.width) // 2
    oy = (sh - screenshot.height) // 2
    shot_bg.paste(screenshot, (ox, oy))
    draw_rounded_rectangle(draw, (sx - 10, sy - 10, sx + sw + 10, sy + sh + 10), 24, "#111d2e", BORDER, 2)
    base.paste(shot_bg, (sx, sy))

    # Content panel.
    px, py, pw, ph = 840, 118, 386, 492
    draw_rounded_rectangle(draw, (px, py, px + pw, py + ph), 28, PANEL, None)
    draw.rectangle((px, py, px + 12, py + ph), fill=segment.accent)
    title_font = load_font(35, True)
    subtitle_font = load_font(19, False)
    body_font = load_font(22, False)
    small_font = load_font(18, False)

    y = py + 32
    for line in wrap_text(draw, segment.title, title_font, pw - 62)[:3]:
        draw.text((px + 34, y), line, font=title_font, fill=INK)
        y += 42
    y += 8
    for line in wrap_text(draw, segment.subtitle, subtitle_font, pw - 62)[:3]:
        draw.text((px + 34, y), line, font=subtitle_font, fill=MUTED)
        y += 25
    y += 16
    for bullet in segment.bullets[:4]:
        draw.ellipse((px + 36, y + 7, px + 48, y + 19), fill=segment.accent)
        bullet_lines = wrap_text(draw, bullet, body_font, pw - 92)[:3]
        for j, line in enumerate(bullet_lines):
            draw.text((px + 60, y + j * 28), line, font=body_font, fill=INK)
        y += max(36, len(bullet_lines) * 28 + 13)

    # Narrator cue.
    cue = f"AI narrator cue · {math.ceil(duration)} sec"
    draw.text((px + 34, py + ph - 42), cue, font=small_font, fill=RED)

    # Lower third caption.
    caption = segment.narration
    caption_lines = wrap_text(draw, caption, load_font(21, False), W - 116)[:2]
    draw.text((52, 633), "Narration", font=load_font(18, True), fill=segment.accent)
    cy = 654
    for line in caption_lines:
        draw.text((52, cy), line, font=load_font(21, False), fill=WHITE)
        cy += 25

    out = FRAMES / f"frame-{index:02d}.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    base.save(out)
    return out


def build_frames_and_srt(audio_duration: float) -> list[Path]:
    shutil.rmtree(FRAMES, ignore_errors=True)
    FRAMES.mkdir(parents=True, exist_ok=True)
    weights = [max(40, len(seg.narration)) for seg in SEGMENTS]
    total_weight = sum(weights)
    durations = [audio_duration * weight / total_weight for weight in weights]
    # Make the final frame absorb rounding drift.
    drift = audio_duration - sum(durations)
    durations[-1] += drift
    frames = [make_frame(seg, i + 1, durations[i]) for i, seg in enumerate(SEGMENTS)]

    def ts(seconds: float) -> str:
        ms = int(round((seconds - int(seconds)) * 1000))
        whole = int(seconds)
        h = whole // 3600
        m = (whole % 3600) // 60
        s = whole % 60
        return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

    now = 0.0
    entries = []
    for idx, (seg, dur) in enumerate(zip(SEGMENTS, durations), 1):
        start = now
        end = min(audio_duration, now + dur)
        text = "\n".join(textwrap.wrap(seg.narration, width=86))
        entries.append(f"{idx}\n{ts(start)} --> {ts(end)}\n{text}\n")
        now = end
    SRT.write_text("\n".join(entries), encoding="utf-8")
    return frames


def build_video(frames: list[Path], audio_duration: float):
    durations = []
    weights = [max(40, len(seg.narration)) for seg in SEGMENTS]
    total_weight = sum(weights)
    for weight in weights:
        durations.append(audio_duration * weight / total_weight)
    durations[-1] += audio_duration - sum(durations)

    concat = ARTIFACTS / "guided_frames" / "concat.txt"
    lines = []
    for frame, dur in zip(frames, durations):
        lines.append(f"file '{frame.as_posix()}'")
        lines.append(f"duration {dur:.3f}")
    lines.append(f"file '{frames[-1].as_posix()}'")
    concat.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp = ARTIFACTS / "your-organization-portal-guided-walkthrough-silent.mp4"
    run([
        "ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(concat),
        "-vf", "fps=30,format=yuv420p", "-c:v", "libx264", "-preset", "veryfast", str(tmp)
    ])
    run([
        "ffmpeg", "-y", "-i", str(tmp), "-i", str(AUDIO), "-map", "0:v:0", "-map", "1:a:0",
        "-c:v", "copy", "-c:a", "aac", "-b:a", "160k", "-shortest", "-movflags", "+faststart", str(VIDEO)
    ])
    tmp.unlink(missing_ok=True)


def add_textbox(slide, x, y, w, h, text, font_size=18, bold=False, color=INK, align=None):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = box.text_frame
    tf.clear()
    tf.word_wrap = True
    tf.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE
    p = tf.paragraphs[0]
    p.text = text
    if align:
        p.alignment = align
    for run in p.runs:
        run.font.size = Pt(font_size)
        run.font.bold = bold
        run.font.color.rgb = RGBColor.from_string(color.replace("#", ""))
    return box


def build_pptx():
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]
    for idx, seg in enumerate(SEGMENTS, 1):
        slide = prs.slides.add_slide(blank)
        bg = slide.background.fill
        bg.solid()
        bg.fore_color.rgb = RGBColor.from_string(NAVY.replace("#", ""))
        # dark header/footer panels
        header = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(0.68))
        header.fill.solid()
        header.fill.fore_color.rgb = RGBColor(11, 22, 40)
        add_textbox(slide, 0.45, 0.18, 3.5, 0.35, "LOST BOYS CYBER", 14, True, WHITE)
        add_textbox(slide, 11.5, 0.18, 1.2, 0.35, f"{idx:02d}/{len(SEGMENTS):02d}", 13, True, seg.accent, PP_ALIGN.RIGHT)
        slide.shapes.add_picture(str(ARTIFACTS / seg.screenshot), Inches(0.55), Inches(1.08), width=Inches(7.55), height=Inches(4.98))
        # right panel
        panel = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(8.55), Inches(1.08), Inches(4.05), Inches(4.98))
        panel.fill.solid(); panel.fill.fore_color.rgb = RGBColor.from_string(PANEL.replace("#", "")); panel.line.color.rgb = RGBColor.from_string(PANEL.replace("#", ""))
        add_textbox(slide, 8.85, 1.38, 3.45, 1.05, seg.title, 26, True, INK)
        add_textbox(slide, 8.85, 2.45, 3.45, 0.62, seg.subtitle, 14, False, MUTED)
        y = 3.2
        for bullet in seg.bullets[:4]:
            add_textbox(slide, 9.05, y, 3.1, 0.42, f"• {bullet}", 14, False, INK)
            y += 0.55
        add_textbox(slide, 8.85, 5.55, 3.45, 0.35, "AI narrator cue included in companion script", 11, True, RED)
        footer_cue = f"Narrator segment: {seg.subtitle}"
        add_textbox(slide, 0.55, 6.34, 12.2, 0.44, footer_cue, 15, True, WHITE)
        add_textbox(slide, 0.55, 6.82, 12.2, 0.25, "Full voiceover script, MP3 narration, SRT captions, and narrated MP4 are included in the asset package.", 10, False, "#cbd5e1")
    prs.save(str(PPTX))


def export_pdf():
    if not shutil.which("soffice"):
        return False
    before = set(ARTIFACTS.glob("*.pdf"))
    run(["soffice", "--headless", "--convert-to", "pdf", "--outdir", str(ARTIFACTS), str(PPTX)])
    return PDF.exists() or set(ARTIFACTS.glob("*.pdf")) != before


def write_readme(audio_duration: float, video_duration: float):
    README.write_text(f"""# Guided Walkthrough Presentation Assets

Generated assets for the Your Organization portal presentation package.

## Files

- `your-organization-portal-guided-walkthrough.pptx` — slide deck with guided talk track text.
- `your-organization-portal-guided-walkthrough.pdf` — rendered shareable PDF export.
- `your-organization-portal-guided-walkthrough-narrated.mp4` — AI-narrated walkthrough video.
- `guided-walkthrough-narration.mp3` — AI narrator voiceover generated with the Hermes TTS provider.
- `guided-walkthrough-narration.md` — editable narration script.
- `your-organization-portal-guided-walkthrough-captions.srt` — caption sidecar for the narrated video.
- `guided_frames/` — generated storyboard frames used by the video.

## Walkthrough order

1. Dashboard: command-center visibility.
2. Task board: governed work lifecycle.
3. Research intake: deliberate routing and gated malware sandboxing.
4. Documents: final-report source of truth.
5. Clients: stakeholder-scoped reporting value.
6. Operator assist: collaboration tied to the work item.
7. Security and governance: MFA, admin controls, audit, and publication gates.
8. Outcome and roadmap: repeatable cyber operating system.

## Media facts

- Narration duration: {audio_duration:.1f} seconds.
- Narrated video duration: {video_duration:.1f} seconds.
- Video resolution: 1280x720.

## Safety note

The demo screenshots and generated walkthrough assets are presentation materials. The offline demo harness uses synthetic temporary state and does not touch live portal data, OpenCTI state, customer material, credentials, or analyst-kit source artifacts.
""", encoding="utf-8")


def main():
    missing = [str(ARTIFACTS / seg.screenshot) for seg in SEGMENTS if not (ARTIFACTS / seg.screenshot).exists()]
    if missing:
        raise SystemExit("Missing screenshots:\n" + "\n".join(missing))
    if not AUDIO.exists():
        raise SystemExit(f"Missing narration audio: {AUDIO}")
    audio_duration = ffprobe_duration(AUDIO)
    frames = build_frames_and_srt(audio_duration)
    build_video(frames, audio_duration)
    build_pptx()
    pdf_exported = export_pdf()
    video_duration = ffprobe_duration(VIDEO)
    write_readme(audio_duration, video_duration)
    print(json.dumps({
        "pptx": str(PPTX),
        "pdf": str(PDF) if pdf_exported else None,
        "video": str(VIDEO),
        "audio": str(AUDIO),
        "captions": str(SRT),
        "readme": str(README),
        "audio_duration": round(audio_duration, 3),
        "video_duration": round(video_duration, 3),
        "frames": len(frames),
    }, indent=2))


if __name__ == "__main__":
    main()
